In [10]:
from mdm.standardize import standardize_name, standardize_street, extract_suite

standardize_name("St. Joseph's Hosp STE 4OO, Inc.")

'SAINT JOSEPH HOSPITAL'

In [11]:
import pandas as pd

erp = pd.read_csv("../data/sample/distributor_alpha_tracing_2026-03.csv", dtype=str)
erp["name_std"] = erp["ship_to_name"].apply(standardize_name)

erp[["ship_to_name", "name_std"]].head(15)

,ship_to_name,name_std
0,OAKMONT IMAGING CENTER,OAKMONT IMAGING CENTER
1,OAKMONT IMAGING CENTER D/B/A OAKMONT HEALTH,OAKMONT IMAGING CENTER
2,LAKEVIEW ORTHOPEDICS,LAKEVIEW ORTHOPEDICS
3,LAKEVIEW ORTHOPEDICS STE 210,LAKEVIEW ORTHOPEDICS
4,LAKEVIEW ORTHOPEDICS,LAKEVIEW ORTHOPEDICS
5,LAKEVIEW ORTHOPEDICS,LAKEVIEW ORTHOPEDICS
6,"NORTHGATE REGIONAL HOSPITAL, INC.",NORTHGATE REGIONAL HOSPITAL
7,NORTHGATE REGIONAL HOSPITAL D/B/A NORTHGATE HE...,NORTHGATE REGIONAL HOSPITAL
8,NORTHGATE REGIONAL HOSPITAL,NORTHGATE REGIONAL HOSPITAL
9,BROOKSIDE SURGERY CTR,BROOKSIDE SURGERY CENTER
10,BROOKSIDE SURGERY CTR,BROOKSIDE SURGERY CENTER
11,BROOKSIDE SURGERY CENTER D/B/A BROOKSIDE HE...,BROOKSIDE SURGERY CENTER
12,BROOKSIDE SURGERY CENTER,BROOKSIDE SURGERY CENTER
13,SAINT LUKE COMMUNITY HOSPITAL D/B/A SAINT HEAL...,SAINT LUKE COMMUNITY HOSPITAL
14,ST LUKE COMMUNITY HOSP,SAINT LUKE COMMUNITY HOSPITAL

In [ ]:
import pandas as pd

erp = pd.read_csv("../data/sample/erp_customer_master.csv", dtype=str)
erp["name_std"] = erp["customer_name"].apply(standardize_name)

erp[["customer_name", "name_std"]].head(15)

                customer_name                       name_std
0         OAKMONT IMAGING CTR         OAKMONT IMAGING CENTER
1              LAKEVIEW ORTHO           LAKEVIEW ORTHOPEDICS
2     NORTHGATE REGIONAL HOSP    NORTHGATE REGIONAL HOSPITAL
3       BROOKSIDE SURGERY CTR       BROOKSIDE SURGERY CENTER
4      ST LUKE COMMUNITY HOSP  SAINT LUKE COMMUNITY HOSPITAL
5               LAKEVIEW HOSP              LAKEVIEW HOSPITAL
6        MERCY OUTPATIENT CTR        MERCY OUTPATIENT CENTER
7   WILLAMETTE OUTPATIENT CTR   WILLAMETTE OUTPATIENT CENTER
8        HARBOR POINT MED CTR    HARBOR POINT MEDICAL CENTER
9   WILLAMETTE OUTPATIENT CTR   WILLAMETTE OUTPATIENT CENTER
10              BAYVIEW ORTHO            BAYVIEW ORTHOPEDICS
11     WILLAMETTE CANCER INST    WILLAMETTE CANCER INSTITUTE
12  GRANITE FALLS CANCER INST  GRANITE FALL CANCER INSTITUTE
13                MERCY ORTHO              MERCY ORTHOPEDICS
14            ST LUKE MED CTR      SAINT LUKE MEDICAL CENTER